Rails.application.routes.draw do
    root 'pages#show', page: 'index'
    get '/kontakt' => 'contact#form'
    post '/kontakt' => 'contact#mail'
    get '/spis-kart' => 'pages#show', page: 'cardlist'
    get '/spis-kart-bs' => 'pages#show', page: 'cardlist-bs'
    get '/spis-kart-da' => 'pages#show', page: 'cardlist-da'
    get '/spis-kart-qp' => 'pages#show', page: 'cardlist-qp'
    get '/spolecznosc' => 'pages#show', page: 'community'
    get '/opis-gry' => 'pages#show', page: 'description'
    get '/dodatki' => 'pages#show', page: 'extensions'
    get '/o-grze' => 'pages#show', page: 'game'
    get '/zasady' => 'pages#show', page: 'rules'
    get '/handel' => 'pages#show', page: 'trade'
    get '/:page' => 'pages#show'
end
